imports:
    - { resource: tables.yml }
services:
    dmzx.whovisitedthistopic.listener:
        class: dmzx\whovisitedthistopic\event\main_listener
        arguments:
            - '@config'
            - '@template'
            - '@dbal.conn'
            - '@user'
            - '@request'
            - '@content.visibility'
            - '@cache'
            - '@pagination'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.whovisitedthistopic.tables.whovisitedthistopic%'
            - '@auth'
            - '%core.adm_relative_path%'
            - '@?files.factory'
        tags:
            - { name: event.listener }
    dmzx.whovisitedthistopic.acplistener:
        class: dmzx\whovisitedthistopic\event\acp_listener
        tags:
            - { name: event.listener }   